insert into Employee (id, Name, Salary, Country, City) values (1, 'Asher', 215500, 'Greece', 'Anthoúsa');
insert into Employee (id, Name, Salary, Country, City) values (2, 'Doralynne', 451165, 'Nigeria', 'Wawa');
insert into Employee (id, Name, Salary, Country, City) values (3, 'Onida', 388121, 'China', 'Heku');
insert into Employee (id, Name, Salary, Country, City) values (4, 'Gwendolyn', 774500, 'China', 'Zhangcunping');
insert into Employee (id, Name, Salary, Country, City) values (5, 'Haleigh', 117280, 'Indonesia', 'Katur');
insert into Employee (id, Name, Salary, Country, City) values (6, 'Tine', 455852, 'Belarus', 'Kokhanava');
insert into Employee (id, Name, Salary, Country, City) values (7, 'Ursuline', 592177, 'Czech Republic', 'Brušperk');
insert into Employee (id, Name, Salary, Country, City) values (8, 'Ruth', 453445, 'Qatar', 'Al Jumaylīyah');
insert into Employee (id, Name, Salary, Country, City) values (9, 'Chalmers', 599389, 'Greece', 'Perístasi');
insert into Employee (id, Name, Salary, Country, City) values (10, 'Perla', 539169, 'China', 'Huimin');
insert into Employee (id, Name, Salary, Country, City) values (11, 'Jerome', 518930, 'Indonesia', 'Rancageneng Satu');
insert into Employee (id, Name, Salary, Country, City) values (12, 'Sandra', 515455, 'China', 'Yishi');
insert into Employee (id, Name, Salary, Country, City) values (13, 'Christa', 242953, 'China', 'Lidian');
insert into Employee (id, Name, Salary, Country, City) values (14, 'Viola', 866621, 'China', 'Lingda');
insert into Employee (id, Name, Salary, Country, City) values (15, 'Rochelle', 355987, 'Indonesia', 'Pasrukrajan Satu');
insert into Employee (id, Name, Salary, Country, City) values (16, 'Marinna', 931671, 'Portugal', 'Santa Valha');
insert into Employee (id, Name, Salary, Country, City) values (17, 'Delainey', 896702, 'Syria', 'Ţayyibat al Imām');
insert into Employee (id, Name, Salary, Country, City) values (18, 'Bree', 684988, 'China', 'Yuli');
insert into Employee (id, Name, Salary, Country, City) values (19, 'Derrick', 711012, 'China', 'Leifeng');
insert into Employee (id, Name, Salary, Country, City) values (20, 'Lanny', 786834, 'Peru', 'Cachimayo');
insert into Employee (id, Name, Salary, Country, City) values (21, 'Bert', 361283, 'Indonesia', 'Lamatuka');
insert into Employee (id, Name, Salary, Country, City) values (22, 'Sheridan', 545767, 'Sweden', 'Karlskoga');
insert into Employee (id, Name, Salary, Country, City) values (23, 'Kaylil', 362318, 'Lebanon', 'Beirut');
insert into Employee (id, Name, Salary, Country, City) values (24, 'Krisha', 314192, 'Ethiopia', 'Addis Ababa');
insert into Employee (id, Name, Salary, Country, City) values (25, 'Rozalie', 854676, 'Indonesia', 'Genyem');
insert into Employee (id, Name, Salary, Country, City) values (26, 'Weston', 321269, 'New Caledonia', 'Ouégoa');
insert into Employee (id, Name, Salary, Country, City) values (27, 'Raimondo', 917222, 'Russia', 'Pridonskoy');
insert into Employee (id, Name, Salary, Country, City) values (28, 'Lonnie', 199338, 'Russia', 'Uritsk');
insert into Employee (id, Name, Salary, Country, City) values (29, 'Wendall', 965026, 'Indonesia', 'Tutnae');
insert into Employee (id, Name, Salary, Country, City) values (30, 'Christoforo', 866710, 'Costa Rica', 'Alajuela');
insert into Employee (id, Name, Salary, Country, City) values (31, 'Sarina', 352735, 'Morocco', 'Tit Mellil');
insert into Employee (id, Name, Salary, Country, City) values (32, 'Frants', 163446, 'China', 'Yuqi');
insert into Employee (id, Name, Salary, Country, City) values (33, 'Vic', 348521, 'China', 'Longbo');
insert into Employee (id, Name, Salary, Country, City) values (34, 'Cordie', 200015, 'Indonesia', 'Krayen');
insert into Employee (id, Name, Salary, Country, City) values (35, 'Corilla', 961101, 'Argentina', 'Ulapes');
insert into Employee (id, Name, Salary, Country, City) values (36, 'Skipper', 691672, 'Indonesia', 'Tagog');
insert into Employee (id, Name, Salary, Country, City) values (37, 'Alejoa', 132557, 'China', 'Nanjia');
insert into Employee (id, Name, Salary, Country, City) values (38, 'Koenraad', 115375, 'Sweden', 'Skara');
insert into Employee (id, Name, Salary, Country, City) values (39, 'Wald', 182444, 'Indonesia', 'Biito');
insert into Employee (id, Name, Salary, Country, City) values (40, 'Noami', 549648, 'Venezuela', 'San Fernando Apure');
insert into Employee (id, Name, Salary, Country, City) values (41, 'Emelda', 968138, 'Democratic Republic of the Congo', 'Mbandaka');
insert into Employee (id, Name, Salary, Country, City) values (42, 'Tamarra', 548282, 'Namibia', 'Mariental');
insert into Employee (id, Name, Salary, Country, City) values (43, 'Hartley', 644113, 'Sweden', 'Västra Frölunda');
insert into Employee (id, Name, Salary, Country, City) values (44, 'Winonah', 306716, 'Russia', 'Mineralnye Vody');
insert into Employee (id, Name, Salary, Country, City) values (45, 'Desiri', 239997, 'Poland', 'Jawornik');
insert into Employee (id, Name, Salary, Country, City) values (46, 'Verne', 418814, 'Canada', 'Notre-Dame-des-Prairies');
insert into Employee (id, Name, Salary, Country, City) values (47, 'Brier', 449911, 'China', 'Jinping');
insert into Employee (id, Name, Salary, Country, City) values (48, 'Mabel', 512602, 'Russia', 'Novokhopërsk');
insert into Employee (id, Name, Salary, Country, City) values (49, 'Allison', 666661, 'Sweden', 'Gävle');
insert into Employee (id, Name, Salary, Country, City) values (50, 'Kylynn', 156454, 'Finland', 'Kaavi');
insert into Employee (id, Name, Salary, Country, City) values (51, 'Elihu', 674872, 'Philippines', 'Bato');
insert into Employee (id, Name, Salary, Country, City) values (52, 'Ogdon', 129368, 'Uruguay', 'Progreso');
insert into Employee (id, Name, Salary, Country, City) values (53, 'Debor', 30852, 'South Korea', 'Hwasun');
insert into Employee (id, Name, Salary, Country, City) values (54, 'Janot', 33016, 'Peru', 'Marcara');
insert into Employee (id, Name, Salary, Country, City) values (55, 'Gustave', 566574, 'Indonesia', 'Gampang');
insert into Employee (id, Name, Salary, Country, City) values (56, 'Bel', 147544, 'China', 'Ruixi');
insert into Employee (id, Name, Salary, Country, City) values (57, 'Serena', 500406, 'Indonesia', 'Poli');
insert into Employee (id, Name, Salary, Country, City) values (58, 'Bronnie', 425410, 'Japan', 'Ishikawa');
insert into Employee (id, Name, Salary, Country, City) values (59, 'Paule', 610011, 'Mexico', 'Santa Maria');
insert into Employee (id, Name, Salary, Country, City) values (60, 'Lyle', 229770, 'Guatemala', 'Santa Cruz Balanyá');
insert into Employee (id, Name, Salary, Country, City) values (61, 'Devora', 627661, 'China', 'Jetaral');
insert into Employee (id, Name, Salary, Country, City) values (62, 'Bibi', 226139, 'Peru', 'Cauday');
insert into Employee (id, Name, Salary, Country, City) values (63, 'Bendix', 333380, 'China', 'Lanzhong');
insert into Employee (id, Name, Salary, Country, City) values (64, 'Anne-marie', 341315, 'Indonesia', 'Sakerta Timur');
insert into Employee (id, Name, Salary, Country, City) values (65, 'Juanita', 636844, 'Russia', 'Beringovskiy');
insert into Employee (id, Name, Salary, Country, City) values (66, 'Conrade', 411616, 'Indonesia', 'Muara');
insert into Employee (id, Name, Salary, Country, City) values (67, 'Pippo', 50645, 'China', 'Dawang');
insert into Employee (id, Name, Salary, Country, City) values (68, 'Jacki', 489911, 'United States', 'Tyler');
insert into Employee (id, Name, Salary, Country, City) values (69, 'Florenza', 300379, 'Bangladesh', 'Pīrgaaj');
insert into Employee (id, Name, Salary, Country, City) values (70, 'Martguerita', 18773, 'Hungary', 'Dunaújváros');
insert into Employee (id, Name, Salary, Country, City) values (71, 'Chicky', 389701, 'China', 'Sanxi');
insert into Employee (id, Name, Salary, Country, City) values (72, 'Yetta', 410446, 'China', 'Liuhe');
insert into Employee (id, Name, Salary, Country, City) values (73, 'Mil', 984370, 'Ukraine', 'Stakhanov');
insert into Employee (id, Name, Salary, Country, City) values (74, 'Dacie', 854881, 'Sweden', 'Göteborg');
insert into Employee (id, Name, Salary, Country, City) values (75, 'Diannne', 3057, 'Indonesia', 'Pacarkeling');
insert into Employee (id, Name, Salary, Country, City) values (76, 'Boote', 900597, 'Brazil', 'Irará');
insert into Employee (id, Name, Salary, Country, City) values (77, 'Hannis', 62311, 'Portugal', 'Mirandela');
insert into Employee (id, Name, Salary, Country, City) values (78, 'Nathanil', 486643, 'United States', 'Wilmington');
insert into Employee (id, Name, Salary, Country, City) values (79, 'Myranda', 850655, 'Laos', 'Pakxong');
insert into Employee (id, Name, Salary, Country, City) values (80, 'Brooke', 987917, 'South Africa', 'Parys');
insert into Employee (id, Name, Salary, Country, City) values (81, 'Ikey', 236489, 'China', 'Luokeng');
insert into Employee (id, Name, Salary, Country, City) values (82, 'Marlowe', 76139, 'Philippines', 'Jarigue');
insert into Employee (id, Name, Salary, Country, City) values (83, 'Gracia', 937055, 'France', 'Golbey');
insert into Employee (id, Name, Salary, Country, City) values (84, 'Cly', 513860, 'Portugal', 'Bombarral');
insert into Employee (id, Name, Salary, Country, City) values (85, 'Pail', 516238, 'Philippines', 'Kaputian');
insert into Employee (id, Name, Salary, Country, City) values (86, 'Vaughan', 680129, 'China', 'Mintian');
insert into Employee (id, Name, Salary, Country, City) values (87, 'Alfie', 321762, 'China', 'Pengbu');
insert into Employee (id, Name, Salary, Country, City) values (88, 'Brooke', 297085, 'Poland', 'Ożarowice');
insert into Employee (id, Name, Salary, Country, City) values (89, 'Quincey', 446392, 'Russia', 'Ostrogozhsk');
insert into Employee (id, Name, Salary, Country, City) values (90, 'Gabriel', 433557, 'Russia', 'Aban');
insert into Employee (id, Name, Salary, Country, City) values (91, 'El', 556850, 'Guatemala', 'Ciudad Vieja');
insert into Employee (id, Name, Salary, Country, City) values (92, 'Benedicto', 17745, 'United Kingdom', 'Manchester');
insert into Employee (id, Name, Salary, Country, City) values (93, 'Sidoney', 526864, 'Dominican Republic', 'Moca');
insert into Employee (id, Name, Salary, Country, City) values (94, 'Karil', 665327, 'Canada', 'Magog');
insert into Employee (id, Name, Salary, Country, City) values (95, 'Emanuel', 825161, 'Sri Lanka', 'Tangalla');
insert into Employee (id, Name, Salary, Country, City) values (96, 'Wade', 918831, 'Venezuela', 'Aguasay');
insert into Employee (id, Name, Salary, Country, City) values (97, 'Huntley', 170494, 'Latvia', 'Gulbene');
insert into Employee (id, Name, Salary, Country, City) values (98, 'Thorin', 888336, 'France', 'Paris 16');
insert into Employee (id, Name, Salary, Country, City) values (99, 'Deloris', 548235, 'China', 'Huoshaoping');
insert into Employee (id, Name, Salary, Country, City) values (100, 'Jayne', 189125, 'China', 'Songgai');
