insert into Employee (id, Name, Salary, Country, City) values (1, 'Mei', '$875572.26', 'Indonesia', 'Seteluk Tengah');
insert into Employee (id, Name, Salary, Country, City) values (2, 'Billy', '$229288.20', 'Czech Republic', 'Hostavice');
insert into Employee (id, Name, Salary, Country, City) values (3, 'Rey', '$222421.00', 'Japan', 'Kamifukuoka');
insert into Employee (id, Name, Salary, Country, City) values (4, 'Harrietta', '$76634.65', 'China', 'Fenghuang');
insert into Employee (id, Name, Salary, Country, City) values (5, 'Odey', '$166648.18', 'Sweden', 'Hisings Kärra');
insert into Employee (id, Name, Salary, Country, City) values (6, 'Hadrian', '$934877.49', 'Philippines', 'San Miguel');
insert into Employee (id, Name, Salary, Country, City) values (7, 'Curtis', '$410055.50', 'Portugal', 'Vale');
insert into Employee (id, Name, Salary, Country, City) values (8, 'Marcellina', '$826218.05', 'United States', 'Omaha');
insert into Employee (id, Name, Salary, Country, City) values (9, 'Sollie', '$214482.28', 'Senegal', 'Goléré');
insert into Employee (id, Name, Salary, Country, City) values (10, 'Jeromy', '$634239.21', 'Philippines', 'Lusacan');
insert into Employee (id, Name, Salary, Country, City) values (11, 'Donnie', '$61567.31', 'France', 'Lille');
insert into Employee (id, Name, Salary, Country, City) values (12, 'Alleyn', '$598907.87', 'Poland', 'Stegna');
insert into Employee (id, Name, Salary, Country, City) values (13, 'My', '$34188.25', 'China', 'Weihe');
insert into Employee (id, Name, Salary, Country, City) values (14, 'Normand', '$519576.78', 'United States', 'Gary');
insert into Employee (id, Name, Salary, Country, City) values (15, 'Cammi', '$440893.78', 'New Zealand', 'Wiri');
insert into Employee (id, Name, Salary, Country, City) values (16, 'Tedmund', '$670983.59', 'Indonesia', 'Karangbadar Kidul');
insert into Employee (id, Name, Salary, Country, City) values (17, 'Munroe', '$821554.69', 'China', 'Nantou');
insert into Employee (id, Name, Salary, Country, City) values (18, 'Gabriellia', '$229892.72', 'Sweden', 'Smålandsstenar');
insert into Employee (id, Name, Salary, Country, City) values (19, 'Vasily', '$834535.35', 'Russia', 'Glotovka');
insert into Employee (id, Name, Salary, Country, City) values (20, 'Vitia', '$766562.37', 'Portugal', 'Alhos Vedros');
insert into Employee (id, Name, Salary, Country, City) values (21, 'Stephanus', '$608920.78', 'China', 'Jianlong');
insert into Employee (id, Name, Salary, Country, City) values (22, 'Noll', '$204914.31', 'Ukraine', 'Richky');
insert into Employee (id, Name, Salary, Country, City) values (23, 'Adlai', '$754564.27', 'China', 'Donglu');
insert into Employee (id, Name, Salary, Country, City) values (24, 'Baron', '$949392.65', 'Iran', 'Tajrīsh');
insert into Employee (id, Name, Salary, Country, City) values (25, 'Kalina', '$754869.60', 'Poland', 'Krasne');
insert into Employee (id, Name, Salary, Country, City) values (26, 'Suzanna', '$205424.35', 'Philippines', 'Comillas Norte');
insert into Employee (id, Name, Salary, Country, City) values (27, 'Marlo', '$281525.28', 'Indonesia', 'Cigaleuh Kulon');
insert into Employee (id, Name, Salary, Country, City) values (28, 'Odille', '$113712.37', 'Sweden', 'Gislaved');
insert into Employee (id, Name, Salary, Country, City) values (29, 'Milt', '$554301.08', 'Uganda', 'Pallisa');
insert into Employee (id, Name, Salary, Country, City) values (30, 'Priscilla', '$539039.85', 'France', 'Sannois');
insert into Employee (id, Name, Salary, Country, City) values (31, 'Dedie', '$728541.31', 'China', 'Fengniancun');
insert into Employee (id, Name, Salary, Country, City) values (32, 'Othilie', '$630559.72', 'Sweden', 'Norrköping');
insert into Employee (id, Name, Salary, Country, City) values (33, 'Kenon', '$928703.21', 'China', 'Fenggao');
insert into Employee (id, Name, Salary, Country, City) values (34, 'Kris', '$520376.48', 'China', 'Shuangtang');
insert into Employee (id, Name, Salary, Country, City) values (35, 'Nerti', '$699448.40', 'Indonesia', 'Banjar Kertasari');
insert into Employee (id, Name, Salary, Country, City) values (36, 'Pedro', '$840400.94', 'Brazil', 'Jaraguá do Sul');
insert into Employee (id, Name, Salary, Country, City) values (37, 'Rubie', '$994104.64', 'Syria', 'Junaynat Raslān');
insert into Employee (id, Name, Salary, Country, City) values (38, 'Garrik', '$433293.78', 'Ukraine', 'Lozova');
insert into Employee (id, Name, Salary, Country, City) values (39, 'Dorise', '$223137.59', 'United States', 'Carson City');
insert into Employee (id, Name, Salary, Country, City) values (40, 'Goldina', '$888317.82', 'Brazil', 'Manoel Urbano');
insert into Employee (id, Name, Salary, Country, City) values (41, 'Paola', '$563289.54', 'Brazil', 'Pombos');
insert into Employee (id, Name, Salary, Country, City) values (42, 'Ninnetta', '$625118.68', 'Poland', 'Puck');
insert into Employee (id, Name, Salary, Country, City) values (43, 'Cecilius', '$457895.73', 'Venezuela', 'Obispos');
insert into Employee (id, Name, Salary, Country, City) values (44, 'Coleman', '$409235.73', 'United States', 'Lakeland');
insert into Employee (id, Name, Salary, Country, City) values (45, 'Phillida', '$913564.59', 'Malaysia', 'Kota Bharu');
insert into Employee (id, Name, Salary, Country, City) values (46, 'Catlaina', '$295836.71', 'Brazil', 'Ibiporã');
insert into Employee (id, Name, Salary, Country, City) values (47, 'Harvey', '$482490.03', 'Japan', 'Yatsuomachi-higashikumisaka');
insert into Employee (id, Name, Salary, Country, City) values (48, 'Cort', '$603884.49', 'China', 'Beiling');
insert into Employee (id, Name, Salary, Country, City) values (49, 'Seamus', '$158327.19', 'China', 'Dawan');
insert into Employee (id, Name, Salary, Country, City) values (50, 'Creight', '$38444.11', 'Sweden', 'Hallstavik');
insert into Employee (id, Name, Salary, Country, City) values (51, 'Stevana', '$983642.19', 'Portugal', 'Camarate');
insert into Employee (id, Name, Salary, Country, City) values (52, 'Rodney', '$901502.47', 'Indonesia', 'Parigi');
insert into Employee (id, Name, Salary, Country, City) values (53, 'Isahella', '$13263.87', 'France', 'Golbey');
insert into Employee (id, Name, Salary, Country, City) values (54, 'Ransell', '$820926.03', 'Croatia', 'Srinjine');
insert into Employee (id, Name, Salary, Country, City) values (55, 'Morlee', '$275701.06', 'Japan', 'Nagareyama');
insert into Employee (id, Name, Salary, Country, City) values (56, 'Elwood', '$753552.79', 'Vietnam', 'Thị Trấn Nguyên Bình');
insert into Employee (id, Name, Salary, Country, City) values (57, 'Adan', '$282601.81', 'Indonesia', 'Mekarjaya Satu');
insert into Employee (id, Name, Salary, Country, City) values (58, 'Dannie', '$518160.21', 'Indonesia', 'Pedamaran');
insert into Employee (id, Name, Salary, Country, City) values (59, 'Elbertine', '$627350.97', 'China', 'Yuncao');
insert into Employee (id, Name, Salary, Country, City) values (60, 'Yelena', '$241810.07', 'Egypt', 'Al Maḩallah al Kubrá');
insert into Employee (id, Name, Salary, Country, City) values (61, 'Lydia', '$288037.90', 'Thailand', 'Roi Et');
insert into Employee (id, Name, Salary, Country, City) values (62, 'Ginny', '$485690.47', 'United States', 'Scranton');
insert into Employee (id, Name, Salary, Country, City) values (63, 'Graehme', '$24485.36', 'Ukraine', 'Volodymyr-Volyns’kyy');
insert into Employee (id, Name, Salary, Country, City) values (64, 'Darin', '$976678.20', 'Ukraine', 'Chervonohryhorivka');
insert into Employee (id, Name, Salary, Country, City) values (65, 'Sheena', '$89451.41', 'Portugal', 'Vale Covo');
insert into Employee (id, Name, Salary, Country, City) values (66, 'Benny', '$64614.30', 'Russia', 'Leninsk');
insert into Employee (id, Name, Salary, Country, City) values (67, 'Benetta', '$140625.16', 'Pakistan', 'Landi Kotal');
insert into Employee (id, Name, Salary, Country, City) values (68, 'Doralin', '$576955.38', 'Russia', 'Golovchino');
insert into Employee (id, Name, Salary, Country, City) values (69, 'Andrus', '$934116.44', 'France', 'Saint-Laurent-du-Var');
insert into Employee (id, Name, Salary, Country, City) values (70, 'Isiahi', '$65493.92', 'Russia', 'Novouzensk');
insert into Employee (id, Name, Salary, Country, City) values (71, 'Karim', '$570722.00', 'Nigeria', 'Gandi');
insert into Employee (id, Name, Salary, Country, City) values (72, 'Neely', '$698744.02', 'Poland', 'Cekcyn');
insert into Employee (id, Name, Salary, Country, City) values (73, 'Marijo', '$267678.75', 'El Salvador', 'San Juan Opico');
insert into Employee (id, Name, Salary, Country, City) values (74, 'Arlene', '$432795.08', 'Portugal', 'Pisões');
insert into Employee (id, Name, Salary, Country, City) values (75, 'Kelsy', '$175809.41', 'Libya', 'Tripoli');
insert into Employee (id, Name, Salary, Country, City) values (76, 'Livvy', '$861361.51', 'Tajikistan', 'Bahorí');
insert into Employee (id, Name, Salary, Country, City) values (77, 'Margaux', '$387921.19', 'Portugal', 'Sobrosa');
insert into Employee (id, Name, Salary, Country, City) values (78, 'Gardiner', '$13190.36', 'China', 'Mangdang');
insert into Employee (id, Name, Salary, Country, City) values (79, 'Tobiah', '$839354.38', 'Poland', 'Karsin');
insert into Employee (id, Name, Salary, Country, City) values (80, 'Wilbur', '$641342.60', 'Vietnam', 'Thới Bình');
insert into Employee (id, Name, Salary, Country, City) values (81, 'Irena', '$106894.60', 'Sint Maarten', 'Philipsburg');
insert into Employee (id, Name, Salary, Country, City) values (82, 'Eirena', '$363779.91', 'Indonesia', 'Banjar Kajanan');
insert into Employee (id, Name, Salary, Country, City) values (83, 'Rad', '$727506.94', 'Sweden', 'Kopparberg');
insert into Employee (id, Name, Salary, Country, City) values (84, 'Cassey', '$863546.71', 'Pakistan', 'Bhiria');
insert into Employee (id, Name, Salary, Country, City) values (85, 'Marylou', '$788910.54', 'Canada', 'Bouctouche');
insert into Employee (id, Name, Salary, Country, City) values (86, 'Odessa', '$274562.88', 'China', 'Qingshanhu');
insert into Employee (id, Name, Salary, Country, City) values (87, 'Clarey', '$11809.86', 'Indonesia', 'Karangsari');
insert into Employee (id, Name, Salary, Country, City) values (88, 'Ernestus', '$887702.50', 'Indonesia', 'Karangagung Timur');
insert into Employee (id, Name, Salary, Country, City) values (89, 'Justinn', '$155244.75', 'Croatia', 'Marina');
insert into Employee (id, Name, Salary, Country, City) values (90, 'Giovanni', '$37297.08', 'Cape Verde', 'Espargos');
insert into Employee (id, Name, Salary, Country, City) values (91, 'Alethea', '$967306.47', 'Japan', 'Saitama');
insert into Employee (id, Name, Salary, Country, City) values (92, 'Rebeka', '$376379.23', 'Nigeria', 'Yajiwa');
insert into Employee (id, Name, Salary, Country, City) values (93, 'Casi', '$698911.70', 'Armenia', 'Goght’');
insert into Employee (id, Name, Salary, Country, City) values (94, 'Lexi', '$596890.54', 'Portugal', 'Martingança');
insert into Employee (id, Name, Salary, Country, City) values (95, 'Ulberto', '$60855.18', 'Ireland', 'Boyle');
insert into Employee (id, Name, Salary, Country, City) values (96, 'Julieta', '$316968.54', 'Germany', 'Münster');
insert into Employee (id, Name, Salary, Country, City) values (97, 'Karmen', '$250100.75', 'Pakistan', 'Sanjwāl');
insert into Employee (id, Name, Salary, Country, City) values (98, 'Westbrook', '$555304.63', 'China', 'Huangqiao');
insert into Employee (id, Name, Salary, Country, City) values (99, 'Moritz', '$834917.17', 'China', 'Yong’an');
insert into Employee (id, Name, Salary, Country, City) values (100, 'Patrica', '$277385.12', 'Cape Verde', 'Pombas');
